# Generated by Django 4.2.3 on 2023-11-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("White", "White"),
                            ("Black", "Black"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                            ("Gray", "Gray"),
                            ("Orange", "Orange"),
                            ("Purple", "Purple"),
                            ("Red", "Red"),
                            ("Brown", "Brown"),
                            ("Yellow", "Yellow"),
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Colorful", "Colorful"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
