# Generated by Django 4.2.3 on 2023-12-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_attributes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttag",
            name="product",
        ),
    ]
