# Generated by Django 4.2.3 on 2023-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_attributes",
            "0003_alter_category_level_alter_category_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="background_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
