# Generated by Django 4.2.3 on 2023-12-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="address",
        ),
    ]
