# Generated by Django 4.2.3 on 2023-12-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("RatherNotSay", "Rather Not Say"),
                    ("Other", "Other"),
                ],
                max_length=16,
            ),
        ),
    ]
