# Generated by Django 4.2.3 on 2023-12-17 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="note",
        ),
        migrations.RemoveField(
            model_name="address",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_address_1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_address_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="user_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="delivery_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="detail_address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="street_name_address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="street_number_address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="cell_phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
