# Generated by Django 4.2.3 on 2023-08-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="Address_name",
            new_name="address_name",
        ),
    ]
