# Generated by Django 4.2.3 on 2023-08-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_address_name_address_address_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("RatherNotSay", "Rather Not Say"),
                    ("Custom", "Custom"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
