# Generated by Django 4.2.3 on 2023-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_paymentinfo"),
    ]

    operations = []
