# Generated by Django 4.2.3 on 2023-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_best_seller",
            field=models.BooleanField(default=False),
        ),
    ]
