# Generated by Django 4.2.3 on 2023-12-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="default_shipping_address",
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("RatherNotSay", "Rather Not Say"),
                    ("Custom", "Custom"),
                ],
                default=1,
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
