# Generated by Django 4.2.3 on 2023-08-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_shop_avatar_shop_background_pic_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="announcement",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
