# Generated by Django 4.2.3 on 2023-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_default_shipping_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_confirmed",
            field=models.BooleanField(default=True),
        ),
    ]
