# Generated by Django 4.2.3 on 2023-08-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_product_processing_max_and_more"),
        ("users", "0008_shop_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("rank", models.PositiveIntegerField(null=True, unique=True)),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="products", to="products.product"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="users.shop",
                    ),
                ),
            ],
        ),
    ]
