# Generated by Django 4.2.3 on 2023-12-17 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_name", models.CharField(max_length=100)),
                ("street_name_address", models.CharField(max_length=100)),
                ("street_number_address", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=5)),
                ("detail_address", models.CharField(max_length=100)),
                ("cell_phone_number", models.CharField(max_length=11)),
                ("delivery_instructions", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
