# Generated by Django 4.2.3 on 2023-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                blank=True,
                default="https://img.freepik.com/free-icon/user_318-644324.jpg",
                null=True,
            ),
        ),
    ]
