# Generated by Django 4.2.3 on 2023-12-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_confirmed",
        ),
    ]
