# Generated by Django 4.2.3 on 2023-12-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="description",
        ),
    ]
