# Generated by Django 4.2.3 on 2023-08-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="is_best_seller",
            new_name="is_star_seller",
        ),
    ]
