# Generated by Django 4.2.3 on 2023-08-16 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_is_best_seller_shop_is_star_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
