# Generated by Django 4.2.3 on 2023-08-16 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_alter_product_category_alter_product_colors_and_more"),
        ("users", "0014_alter_shop_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="product",
            field=models.ManyToManyField(related_name="+", to="products.product"),
        ),
        migrations.AlterField(
            model_name="section",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="users.shop",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.address",
            ),
        ),
        migrations.RemoveField(
            model_name="shop",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="users.address"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
