# Generated by Django 4.2.3 on 2023-08-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_shop_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="user",
            new_name="users",
        ),
    ]
