# Generated by Django 4.2.3 on 2023-08-28 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_shop_shop_policy_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=datetime.date(1977, 7, 7), null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("RatherNotSay", "Rather Not Say"),
                    ("Custom", "Custom"),
                ],
                default="Female",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
