# Generated by Django 4.2.3 on 2023-08-28 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.address",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="cancellation",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_policy_updated_at",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=datetime.date(1977, 7, 7), null=True),
        ),
    ]
