# Generated by Django 4.2.3 on 2023-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_shop_description_title_alter_shop_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="image_1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="image_2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="image_3",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="image_4",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="image_5",
            field=models.URLField(blank=True, null=True),
        ),
    ]
