# Generated by Django 4.2.3 on 2023-11-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("product_collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="product",
            field=models.ManyToManyField(
                related_name="collection", to="products.product"
            ),
        ),
    ]
