# Generated by Django 4.2.3 on 2023-12-17 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product_collections", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="user",
            field=models.ManyToManyField(
                related_name="collection", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
