# Generated by Django 4.2.3 on 2023-11-25 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_initial"),
        ("favorites", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriteshop",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites_shops",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favoriteProduct",
            name="products",
            field=models.ManyToManyField(
                related_name="favorites_item", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="favoriteProduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
