# Generated by Django 4.2.3 on 2023-11-28 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_shop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favorites", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoriteproduct",
            name="products",
            field=models.ManyToManyField(
                related_name="favorites_product", to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="favoriteproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
