# Generated by Django 4.2.3 on 2023-11-28 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_shop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favorites", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteItem",
            new_name="FavoriteProduct",
        ),
    ]
