# Generated by Django 4.2.3 on 2023-08-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favoriteshop",
            old_name="shop",
            new_name="shops",
        ),
        migrations.RenameField(
            model_name="favoritesitem",
            old_name="product",
            new_name="products",
        ),
    ]
