# Generated by Django 4.2.3 on 2023-08-17 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_alter_product_category_alter_product_colors_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favorites", "0004_rename_shop_favoriteshop_shops_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoritesItem",
            new_name="FavoriteItem",
        ),
    ]
