# Generated by Django 4.2.3 on 2023-11-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_attributes", "0001_initial"),
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="categories",
            field=models.ManyToManyField(blank=True, to="product_attributes.category"),
        ),
    ]
