# Generated by Django 4.2.3 on 2023-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0003_voucher_discount_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount_value",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
