# Generated by Django 4.2.3 on 2023-08-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0003_delete_update"),
        ("discount", "0004_sale_discount_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucher",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="voucher",
            name="products",
        ),
        migrations.RemoveField(
            model_name="voucher",
            name="variants",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
        migrations.DeleteModel(
            name="voucher",
        ),
    ]
