# Generated by Django 4.2.3 on 2023-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0028_delete_productvariant"),
        ("discount", "0005_remove_voucher_categories_remove_voucher_products_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entire_order", "Entire order"),
                            ("shipping", "Shipping"),
                            (
                                "specific_product",
                                "Specific products, collections and categories",
                            ),
                        ],
                        default="entire_order",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "discount_value_type",
                    models.CharField(
                        choices=[("fixed", "fixed"), ("percentage", "%")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                ("discount_value", models.CharField(max_length=10)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="products.category"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="voucher", to="products.product"
                    ),
                ),
                (
                    "variants",
                    models.ManyToManyField(blank=True, to="products.variantvalue"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("fixed", "fixed"), ("percentage", "%")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("discount_value", models.CharField(max_length=10)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="products.category"),
                ),
                ("products", models.ManyToManyField(blank=True, to="products.product")),
                (
                    "variants",
                    models.ManyToManyField(blank=True, to="products.variantvalue"),
                ),
            ],
        ),
    ]
