# Generated by Django 4.2.3 on 2023-11-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0006_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="variants",
        ),
        migrations.RemoveField(
            model_name="voucher",
            name="variants",
        ),
    ]
