# Generated by Django 4.2.3 on 2023-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseline",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
