# Generated by Django 4.2.3 on 2023-12-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseline",
            name="order_date",
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="purchased_options",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
