# Generated by Django 4.2.3 on 2023-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0002_purchaseline_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseline",
            name="order_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
