# Generated by Django 4.2.3 on 2023-12-26 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0010_alter_product_item_height_alter_product_item_length_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchases", "0003_remove_purchaseline_order_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_lines",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_lines",
                to="purchases.purchase",
            ),
        ),
    ]
