# Generated by Django 4.2.3 on 2023-12-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0004_alter_purchase_user_alter_purchaseline_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseline",
            name="product_name",
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="product_price",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="product_thumbnail",
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
