# Generated by Django 4.2.3 on 2024-01-04 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "purchases",
            "0005_purchaseline_product_name_purchaseline_product_price_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseline",
            old_name="purchased_options",
            new_name="purchased_option",
        ),
        migrations.RenameField(
            model_name="purchaseline",
            old_name="product_price",
            new_name="purchased_price",
        ),
    ]
