# Generated by Django 4.2.3 on 2023-12-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_variants", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="is_price_vary",
        ),
        migrations.RemoveField(
            model_name="variation",
            name="is_quantity_vary",
        ),
        migrations.RemoveField(
            model_name="variation",
            name="is_sku_vary",
        ),
        migrations.AlterField(
            model_name="variation",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="variationoption",
            name="name",
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="variationoption",
            name="variation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="product_variants.variation",
            ),
            preserve_default=False,
        ),
    ]
