# Generated by Django 4.2.3 on 2023-12-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_variants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variationoption",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
