# Generated by Django 4.2.3 on 2023-12-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_variants", "0003_variation_order_variationoption_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
