# Generated by Django 4.2.3 on 2023-11-25 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.address",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="users",
            field=models.ManyToManyField(
                related_name="shop", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="product",
            field=models.ManyToManyField(related_name="+", to="products.product"),
        ),
        migrations.AddField(
            model_name="section",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="shops.shop",
            ),
        ),
    ]
