# Generated by Django 4.2.3 on 2023-11-26 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shops", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="users",
        ),
        migrations.AddField(
            model_name="shop",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
