# Generated by Django 4.2.3 on 2023-11-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
        ("shops", "0003_remove_shop_users_shop_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="product",
            field=models.ManyToManyField(
                related_name="sections", to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="shops.shop",
            ),
        ),
    ]
