# Generated by Django 4.2.3 on 2023-12-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_rename_cancellation_shop_auto_renewal_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="short_description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
