# Generated by Django 4.2.3 on 2023-12-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_alter_shop_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
