# Generated by Django 4.2.3 on 2023-11-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_alter_section_product_alter_section_shop"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShopTag",
        ),
    ]
