# Generated by Django 4.2.3 on 2023-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_remove_section_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shop",
            name="register_step",
            field=models.IntegerField(default=1),
        ),
    ]
