# Generated by Django 4.2.3 on 2023-11-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_shop_is_activated_shop_register_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="short_description",
            field=models.CharField(default="", max_length=256),
        ),
    ]
