# Generated by Django 4.2.3 on 2023-11-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_shopvideo_shopimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopimage",
            name="order",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
