# Generated by Django 4.2.3 on 2023-11-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0010_shopimage_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="rank",
            new_name="order",
        ),
    ]
