# Generated by Django 4.2.3 on 2023-11-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0011_rename_rank_section_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shopimage",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
