# Generated by Django 4.2.3 on 2023-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0012_alter_section_order_alter_shopimage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shopimage",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
