# Generated by Django 4.2.3 on 2023-11-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0013_alter_section_order_alter_shopimage_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="image_1",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="image_2",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="image_3",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="image_4",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="image_5",
        ),
    ]
