# Generated by Django 4.2.3 on 2023-11-30 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0014_remove_shop_image_1_remove_shop_image_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="section",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
