# Generated by Django 4.2.3 on 2023-12-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0015_section_created_at_section_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
