# Generated by Django 4.2.3 on 2023-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0016_alter_shop_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
