# Generated by Django 4.2.3 on 2023-08-09 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_reviewreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="raitng_customer_service",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="raitng_item_quality",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="raitng_shipping",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
