# Generated by Django 4.2.3 on 2023-12-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_section_order"),
        ("reviews", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=512)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="ReviewPhoto",
            new_name="ReviewImage",
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.CharField(max_length=512),
        ),
        migrations.DeleteModel(
            name="ReviewReply",
        ),
        migrations.AddField(
            model_name="reviewresponse",
            name="review",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewresponse",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="shops.shop",
            ),
        ),
    ]
