# Generated by Django 4.2.3 on 2023-08-16 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_raitng_customer_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewphoto",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="reviews.review",
            ),
        ),
    ]
