# Generated by Django 4.2.3 on 2023-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_reviewphoto_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewphoto",
            name="image",
            field=models.URLField(),
        ),
    ]
