# Generated by Django 4.2.3 on 2023-12-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_reviewresponse_rename_reviewphoto_reviewimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="purchased_options",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
