# Generated by Django 4.2.3 on 2023-12-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_review_purchased_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
