# Generated by Django 4.2.3 on 2024-01-04 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0007_remove_review_purchased_options_review_purchase"),
    ]

    operations = []
