# Generated by Django 4.2.3 on 2023-08-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_reviewreply_shop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewreply",
            name="shop",
        ),
    ]
