# Generated by Django 4.2.3 on 2023-08-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_rename_user_shop_users"),
        ("reviews", "0009_reviewreply_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewreply",
            name="shop",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply",
                to="users.shop",
            ),
        ),
    ]
