# Generated by Django 4.2.3 on 2023-08-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chattingroom",
            old_name="user1",
            new_name="users",
        ),
        migrations.RemoveField(
            model_name="chattingroom",
            name="user2",
        ),
    ]
