# Generated by Django 4.2.3 on 2023-08-01 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("updates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discount", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="discount.voucher"
            ),
        ),
    ]
