# Generated by Django 4.2.3 on 2024-01-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("cart", "0001_initial"),
        ("product_variants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartlines",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="cartline",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartlines",
                to="product_variants.productvariant",
            ),
        ),
    ]
