# Generated by Django 4.2.3 on 2023-08-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0027_alter_variantvalue_option"),
        ("cart", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartline",
            name="variant",
        ),
        migrations.AddField(
            model_name="cartline",
            name="variant",
            field=models.ManyToManyField(related_name="+", to="products.variantvalue"),
        ),
    ]
