# Generated by Django 4.2.3 on 2023-08-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_delete_productvariant"),
        ("cart", "0004_remove_cartline_variant_cartline_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="cartline",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartline",
                to="products.product",
            ),
        ),
    ]
