# Generated by Django 4.2.3 on 2023-08-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_delete_productvariant"),
        ("cart", "0005_remove_cart_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartline",
                to="products.product",
            ),
        ),
    ]
