# Generated by Django 4.2.3 on 2023-08-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_cartline_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartline",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartline",
                to="cart.cart",
            ),
        ),
    ]
