# Generated by Django 4.2.3 on 2023-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_delete_productvariant"),
        ("cart", "0008_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartline",
            name="variant",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="products.variantvalue"
            ),
        ),
    ]
