# Generated by Django 4.2.3 on 2023-11-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_alter_cartline_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartline",
            name="variant",
        ),
    ]
