# Generated by Django 4.2.3 on 2023-11-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0047_product_materials_delete_productmaterial"),
        ("cart", "0010_remove_cartline_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartline",
            name="product",
        ),
        migrations.AddField(
            model_name="cartline",
            name="options",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="products.productvariant"
            ),
        ),
    ]
