# Generated by Django 4.2.3 on 2023-11-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_remove_cartline_product_cartline_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartline",
            name="personalization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
