# Generated by Django 4.2.3 on 2023-11-06 06:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0047_product_materials_delete_productmaterial"),
        ("cart", "0012_cartline_personalization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartline",
            name="options",
        ),
        migrations.AddField(
            model_name="cartline",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartlines",
                to="products.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="cartline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
