# Generated by Django 4.2.3 on 2023-11-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0047_product_materials_delete_productmaterial"),
        ("cart", "0013_remove_cartline_options_cartline_product_variant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartline",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartlines",
                to="products.productvariant",
            ),
        ),
    ]
