# Generated by Django 4.2.3 on 2023-11-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0016_alter_cartline_product_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartline",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartlines",
                to="cart.cart",
            ),
        ),
    ]
