# Generated by Django 4.2.3 on 2023-11-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0048_product_is_active"),
        ("cart", "0017_alter_cartline_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartline",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartlines",
                to="products.productvariant",
            ),
        ),
    ]
