# Generated by Django 4.2.3 on 2023-12-17 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shops.shop",
            ),
        ),
    ]
