# Generated by Django 4.2.3 on 2023-12-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
    ]
