# Generated by Django 4.2.3 on 2023-08-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_delete_payment"),
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderline",
            name="variant",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderLine",
        ),
    ]
