# Generated by Django 4.2.3 on 2023-12-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_initial"),
        ("order", "0003_remove_order_billing_address_and_more"),
    ]

    operations = []
