# Generated by Django 4.2.3 on 2023-11-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CategoryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail_name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("White", "White"),
                            ("Black", "Black"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                            ("Gray", "Gray"),
                            ("Orange", "Orange"),
                            ("Purple", "Purple"),
                            ("Red", "Red"),
                            ("Brown", "Brown"),
                            ("Yellow", "Yellow"),
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Colorful", "Colorful"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("original_price", models.PositiveIntegerField(blank=True, null=True)),
                ("price", models.PositiveIntegerField()),
                (
                    "quantity",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                ("sku", models.CharField(blank=True, max_length=140, null=True)),
                (
                    "made_by",
                    models.CharField(
                        choices=[
                            ("I did", "I did"),
                            ("A memeber of my shop", "A memeber of my shop"),
                            ("Another company or person", "Another company or person"),
                        ],
                        default="I did",
                        max_length=140,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("A finished product", "A finished product"),
                            (
                                "A supply or tool to make things",
                                "A supply or tool to make things",
                            ),
                        ],
                        default="A finished product",
                        max_length=140,
                    ),
                ),
                (
                    "product_creation_date",
                    models.CharField(
                        choices=[
                            ("Made To Order", "Made To Order"),
                            ("2020-2023", "2020-2023"),
                            ("2010-2019", "2010-2019"),
                            ("2000-2009", "2010-2009"),
                            ("Before 2000", "Before 2000"),
                            ("1990-1999", "1990-1999"),
                            ("1980-1989", "1980-1989"),
                            ("1970-1979", "1970-1979"),
                            ("1960-1969", "1960-1969"),
                            ("1950-1959", "1950-1959"),
                            ("1940-1949", "1940-1949"),
                            ("1930-1939", "1930-1939"),
                            ("1920-1929", "1920-1929"),
                            ("1910-1919", "1910-1919"),
                            ("1900-1909", "1900-1909"),
                            ("1800-1899", "1800-1899"),
                            ("1700-1799", "1790-1799"),
                            ("Before 1700", "Before 1700"),
                        ],
                        default="Made To Order",
                        max_length=140,
                    ),
                ),
                (
                    "product_item_type",
                    models.CharField(
                        choices=[("Handmade", "Handmade"), ("Vintage", "Vintage")],
                        default="Handmade",
                        max_length=140,
                    ),
                ),
                ("processing_min", models.CharField(default=3, max_length=32)),
                ("processing_max", models.CharField(default=7, max_length=32)),
                ("shipping_price", models.CharField(default=0, max_length=32)),
                ("item_weight", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "item_weight_unit",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "item_length",
                    models.CharField(blank=True, default=20, max_length=32, null=True),
                ),
                (
                    "item_width",
                    models.CharField(blank=True, default=60, max_length=32, null=True),
                ),
                (
                    "item_height",
                    models.CharField(blank=True, default=90, max_length=32, null=True),
                ),
                ("has_variations", models.BooleanField(default=False)),
                ("thumbnail", models.URLField()),
                ("order_count", models.IntegerField(blank=True, default=0)),
                ("is_best_seller", models.BooleanField(default=False)),
                ("is_return_exchange_available", models.BooleanField(default=False)),
                ("is_frame_included", models.BooleanField(default=False)),
                ("is_giftcard_available", models.BooleanField(default=False)),
                ("is_gift_wrapping_available", models.BooleanField(default=False)),
                ("is_customizable", models.BooleanField(default=False)),
                ("is_artant_star", models.BooleanField(default=False)),
                ("is_artant_choice", models.BooleanField(default=False)),
                ("is_digital", models.BooleanField(default=False)),
                ("is_personalization_enabled", models.BooleanField(default=False)),
                ("is_personalization_optional", models.BooleanField(default=False)),
                (
                    "personalization_guide",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("video", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_sku_vary", models.BooleanField(default=False)),
                ("is_price_vary", models.BooleanField(default=False)),
                ("is_quantity_vary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "variation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProductTimestamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="TTime Stamp"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timestamps",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
