# Generated by Django 4.2.3 on 2023-08-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CategoryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail_name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="DetailValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "made_by",
                    models.CharField(
                        choices=[
                            ("I did", "I did"),
                            ("A memeber of my shop", "A memeber of my my shop"),
                            ("Another company or person", "Another company or person"),
                        ],
                        max_length=140,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("A finished product", "A finished product"),
                            (
                                "A supply or tool to make things",
                                "A supply or tool to make things",
                            ),
                        ],
                        max_length=140,
                    ),
                ),
                (
                    "product_creation_date",
                    models.CharField(
                        choices=[
                            ("Made To Order", "Made To Order"),
                            ("2020-2023", "2020-2023"),
                            ("2010-2019", "2010-2019"),
                            ("2000-2009", "2010-2009"),
                            ("Before 2000", "Before 2000"),
                            ("1990-1999", "1990-1999"),
                            ("1980-1989", "1980-1989"),
                            ("1970-1979", "1970-1979"),
                            ("1960-1969", "1960-1969"),
                            ("1950-1959", "1950-1959"),
                            ("1940-1949", "1940-1949"),
                            ("1930-1939", "1930-1939"),
                            ("1920-1929", "1920-1929"),
                            ("1910-1919", "1910-1919"),
                            ("1900-1909", "1900-1909"),
                            ("1800-1899", "1800-1899"),
                            ("1700-1799", "1790-1799"),
                            ("Before 1700", "Before 1700"),
                        ],
                        max_length=140,
                    ),
                ),
                ("processing_time", models.CharField(max_length=32)),
                ("shipping_price", models.CharField(max_length=32)),
                ("category", models.ManyToManyField(to="products.category")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "details",
                    models.ManyToManyField(
                        related_name="details", to="products.detailvalue"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=32)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=32)),
                (
                    "options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.variantoption",
                    ),
                ),
                (
                    "product_variant",
                    models.ManyToManyField(
                        related_name="variants_values", to="products.productvariant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("video", models.FileField(upload_to="")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=32)),
                (
                    "product",
                    models.ManyToManyField(related_name="tag", to="products.product"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
