# Generated by Django 4.2.3 on 2023-08-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.shop"
            ),
        ),
        migrations.AddField(
            model_name="detailvalue",
            name="detail_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.categorydetail",
            ),
        ),
        migrations.AddField(
            model_name="detailvalue",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="categorydetail",
            name="category",
            field=models.ManyToManyField(
                related_name="details", to="products.category"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
            ),
        ),
    ]
