# Generated by Django 4.2.3 on 2023-11-25 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproducttimestamp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timestamps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productvideo",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="option_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants_as_option_one",
                to="products.variationoption",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="option_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants_as_option_two",
                to="products.variationoption",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="producttag",
            name="product",
            field=models.ManyToManyField(related_name="tags", to="products.product"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="product", to="products.category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="materials",
            field=models.ManyToManyField(blank=True, to="products.material"),
        ),
        migrations.AddField(
            model_name="product",
            name="primary_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_color_products",
                to="products.color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="secondary_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_color_products",
                to="products.color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="detailvalue",
            name="detail_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.categorydetail",
            ),
        ),
        migrations.AddField(
            model_name="detailvalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="categorydetail",
            name="category",
            field=models.ManyToManyField(
                related_name="details", to="products.category"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
            ),
        ),
    ]
