# Generated by Django 4.2.3 on 2023-08-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_detailvalue_product_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailvalue",
            name="value",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
