# Generated by Django 4.2.3 on 2023-12-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_discount",
            field=models.BooleanField(default=False),
        ),
    ]
