# Generated by Django 4.2.3 on 2023-11-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_tag_producttag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
