# Generated by Django 4.2.3 on 2023-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_is_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
