# Generated by Django 4.2.3 on 2023-11-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
