# Generated by Django 4.2.3 on 2023-11-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_material_name_alter_producttag_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producttag",
            old_name="name",
            new_name="tag",
        ),
    ]
