# Generated by Django 4.2.3 on 2023-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_detailvalue_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="details",
        ),
        migrations.RemoveField(
            model_name="variantvalue",
            name="product_variant",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant",
            field=models.ManyToManyField(
                related_name="variant", to="products.variantvalue"
            ),
        ),
    ]
