# Generated by Django 4.2.3 on 2023-08-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_productvariant_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
