# Generated by Django 4.2.3 on 2023-11-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productimage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
