# Generated by Django 4.2.3 on 2023-12-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_discount_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_artant_star",
        ),
        migrations.AddField(
            model_name="product",
            name="item_length_unit",
            field=models.CharField(
                blank=True,
                choices=[("m", "Meter"), ("cm", "Centimeter")],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_weight_unit",
            field=models.CharField(
                blank=True,
                choices=[("kg", "Kilogram"), ("g", "Gram")],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
