# Generated by Django 4.2.3 on 2023-08-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_birthday"),
        ("products", "0007_alter_product_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isBestSeller",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="category", to="products.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop",
                to="users.shop",
            ),
        ),
    ]
