# Generated by Django 4.2.3 on 2023-12-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_shipping_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_rate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
