# Generated by Django 4.2.3 on 2023-12-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="made_by",
            field=models.CharField(
                choices=[
                    ("I did", "I did"),
                    ("A member of my shop", "A memeber of my shop"),
                    ("Another company or person", "Another company or person"),
                ],
                default="I did",
                max_length=140,
            ),
        ),
    ]
