# Generated by Django 4.2.3 on 2023-08-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_isbestseller_alter_product_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="isBestSeller",
            new_name="is_best_seller",
        ),
    ]
