# Generated by Django 4.2.3 on 2023-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_discount_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="item_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_weight",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="order_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
