# Generated by Django 4.2.3 on 2023-12-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_attributes", "0003_remove_producttag_product"),
        ("products", "0009_alter_product_made_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                related_name="products", to="product_attributes.producttag"
            ),
        ),
    ]
