# Generated by Django 4.2.3 on 2023-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_original_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="order_count",
            field=models.IntegerField(default=0),
        ),
    ]
