# Generated by Django 4.2.3 on 2023-08-09 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_userproducttimestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imaegs",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.URLField(),
        ),
    ]
