# Generated by Django 4.2.3 on 2023-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_remove_product_is_best_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="processing_max",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="processing_min",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
