# Generated by Django 4.2.3 on 2023-08-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_product_processing_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_star_seller",
            field=models.BooleanField(default=False),
        ),
    ]
