# Generated by Django 4.2.3 on 2023-08-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_product_is_star_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cart_count",
            field=models.IntegerField(default=0),
        ),
    ]
