# Generated by Django 4.2.3 on 2023-08-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_product_cart_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_gift_wrapping_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_return_exchange_available",
            field=models.BooleanField(default=False),
        ),
    ]
