# Generated by Django 4.2.3 on 2023-08-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_product_is_gift_wrapping_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("White", "White"),
                    ("Black", "Black"),
                    ("Blue", "Blue"),
                    ("Green", "Green"),
                    ("Gray", "Gray"),
                    ("Orange", "Orange"),
                    ("Purple", "Purple"),
                    ("Red", "Red"),
                    ("Brown", "Brown"),
                    ("Yellow", "Yellow"),
                    ("Gold", "Gold"),
                    ("Silver", "Silver"),
                    ("Colorful", "Colorful"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
