# Generated by Django 4.2.3 on 2023-08-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_product_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_star_seller",
            new_name="is_best_seller",
        ),
    ]
