# Generated by Django 4.2.3 on 2023-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_rename_is_star_seller_product_is_best_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_artant_choice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_artant_star",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_frame_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_giftcard_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="product_item_type",
            field=models.CharField(
                choices=[("Handmade", "Handmade"), ("Vintage", "Vintage")],
                default="Handmade",
                max_length=140,
            ),
        ),
    ]
