# Generated by Django 4.2.3 on 2023-08-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_product_is_artant_choice_product_is_artant_star_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("White", "White"),
                            ("Black", "Black"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                            ("Gray", "Gray"),
                            ("Orange", "Orange"),
                            ("Purple", "Purple"),
                            ("Red", "Red"),
                            ("Brown", "Brown"),
                            ("Yellow", "Yellow"),
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Colorful", "Colorful"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(related_name="colors", to="products.color"),
        ),
    ]
