# Generated by Django 4.2.3 on 2023-08-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_is_best_seller_shop_is_star_seller"),
        ("products", "0023_color_remove_product_color_product_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="product", to="products.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(related_name="product", to="products.color"),
        ),
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="users.shop",
            ),
        ),
    ]
