# Generated by Django 4.2.3 on 2023-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_alter_product_category_alter_product_colors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variantoption",
            old_name="option",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="variantvalue",
            old_name="options",
            new_name="option",
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="variant",
            field=models.ManyToManyField(
                related_name="variant", to="products.variantoption"
            ),
        ),
    ]
