# Generated by Django 4.2.3 on 2023-08-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_rename_option_variantoption_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="name",
        ),
    ]
