# Generated by Django 4.2.3 on 2023-08-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0026_remove_productvariant_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantvalue",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="value",
                to="products.variantoption",
            ),
        ),
    ]
