# Generated by Django 4.2.3 on 2023-08-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_cartline_variant_cartline_variant"),
        ("discount", "0005_remove_voucher_categories_remove_voucher_products_and_more"),
        ("order", "0004_remove_orderline_order_remove_orderline_variant_and_more"),
        ("products", "0027_alter_variantvalue_option"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
