# Generated by Django 4.2.3 on 2023-08-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_delete_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cart_count",
        ),
    ]
