# Generated by Django 4.2.3 on 2023-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0029_remove_product_cart_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="processing_max",
            field=models.CharField(default=7, max_length=32),
        ),
        migrations.AlterField(
            model_name="product",
            name="processing_min",
            field=models.CharField(default=3, max_length=32),
        ),
    ]
