# Generated by Django 4.2.3 on 2023-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0030_alter_product_original_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_price",
            field=models.CharField(default=0, max_length=32),
        ),
    ]
