# Generated by Django 4.2.3 on 2023-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0032_alter_product_item_height_alter_product_item_length_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="product", to="products.color"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="order_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
