# Generated by Django 4.2.3 on 2023-10-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0033_alter_product_colors_alter_product_order_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
    ]
