# Generated by Django 4.2.3 on 2023-10-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0034_tag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
