# Generated by Django 4.2.3 on 2023-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0035_delete_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttag",
            name="product",
            field=models.ManyToManyField(related_name="tags", to="products.product"),
        ),
    ]
