# Generated by Django 4.2.3 on 2023-11-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_remove_orderline_variant"),
        ("discount", "0007_remove_sale_variants_remove_voucher_variants"),
        ("cart", "0010_remove_cartline_variant"),
        ("purchases", "0004_remove_purchaseline_variant"),
        ("products", "0039_remove_product_colors_product_primary_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_sku_vary", models.BooleanField(default=False)),
                ("is_price_vary", models.BooleanField(default=False)),
                ("is_quantity_vary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                (
                    "variation_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options_one",
                        to="products.variation",
                    ),
                ),
                (
                    "variation_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options_two",
                        to="products.variation",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="variantvalue",
            name="option",
        ),
        migrations.DeleteModel(
            name="VariantOption",
        ),
        migrations.DeleteModel(
            name="VariantValue",
        ),
    ]
