# Generated by Django 4.2.3 on 2023-11-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0040_variation_variationoption_remove_variantvalue_option_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variationoption",
            name="name",
        ),
    ]
