# Generated by Django 4.2.3 on 2023-11-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0041_remove_variationoption_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variationoption",
            name="is_visible",
        ),
        migrations.RemoveField(
            model_name="variationoption",
            name="price",
        ),
        migrations.RemoveField(
            model_name="variationoption",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="variationoption",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="variationoption",
            name="variation_one",
        ),
        migrations.RemoveField(
            model_name="variationoption",
            name="variation_two",
        ),
        migrations.AddField(
            model_name="variationoption",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="variationoption",
            name="variation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.variation",
            ),
        ),
    ]
