# Generated by Django 4.2.3 on 2023-11-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0042_remove_variationoption_is_visible_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "option_one",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_as_option_one",
                        to="products.variationoption",
                    ),
                ),
                (
                    "option_two",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_as_option_two",
                        to="products.variationoption",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
