# Generated by Django 4.2.3 on 2023-11-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0043_productvariant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="quantity",
        ),
    ]
