# Generated by Django 4.2.3 on 2023-11-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0044_rename_stock_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
