# Generated by Django 4.2.3 on 2023-11-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0045_product_sku_alter_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="personalization_guide",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
