# Generated by Django 4.2.3 on 2023-11-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0046_product_personalization_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="materials",
            field=models.ManyToManyField(blank=True, to="products.material"),
        ),
        migrations.DeleteModel(
            name="ProductMaterial",
        ),
    ]
