# Generated by Django 4.2.3 on 2023-11-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0047_product_materials_delete_productmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
